#pragma once

#include "BleDefine.h"
#include "BleOpCode.h"

#define BLE_GROUP_OFFSET 0xC000

#define SYSTEM_REQ 0xFFE9
#define APP_REQ 0xFFE8
#define RAL_MAGIC 0x0428

#define RD_VENDOR_ID 0x0211

#define RD_OPCODE_PROVISION 0xE0
#define RD_OPCODE_PROVISION_RSP 0xE1
#define RD_OPCODE_CONFIG 0xE2
#define RD_OPCODE_CONFIG_RSP 0xE3

#define RD_OPCODE_SENSOR_RSP 0x52

#define RD_HEADER_PROVISION_SET_GW_ADDR 0x0002
#define RD_HEADER_PROVISION_GET_DEV_TYPE 0x0003
#define RD_HEADER_SATAUS_POWER 0x0001
#define RD_HEADER_REMOTE_MODULE_DC_TYPE 0x0002
#define RD_HEADER_REMOTE_MUL_RSP_SCENE_ACTIVE 0x0502
#define RD_HEADER_REMOTE_MODULE_AC_TYPE 0x0003
#define RD_HEADER_LIGHT_SENSOR_MODULE_TYPE 0x0004
#define RD_HEADER_PIR_SENSOR_MODULE_TYPE 0x0005

#define RD_HEADER_CONFIG_SET_SCENE_SWITCH_SCENE_DC 0x0102
#define RD_HEADER_CONFIG_DEL_SCENE_SWITCH_SCENE_DC 0x0202
#define RD_HEADER_CONFIG_SET_SCENE_SWITCH_SCENE_AC 0x0103
#define RD_HEADER_CONFIG_DEL_SCENE_SWITCH_SCENE_AC 0x0203
#define RD_HEADER_RSP_LIGHT_SENSOR 0x0104
#define RD_HEADER_CONFIG_SET_SCENE_PIR_LIGHT_SENSOR 0x0145
#define RD_HEADER_CONFIG_DEL_SCENE_PIR_LIGHT_SENSOR 0x0245
#define RD_HEADER_CONFIG_SET_TIME_ACTION_PIR_LIGHT_SENSOR 0x0345
#define RD_HEADER_CONFIG_SET_MODE_ACTION_PIR_LIGHT_SENSOR 0x0445
#define RD_HEADER_CONFIG_SET_SENSI_PIR_LIGHT_SENSOR 0x0545
#define RD_HEADER_RSP_PIR_LIGHT_SENSOR_STARTUP 0x0645
#define RD_HEADER_CONFIG_SET_DISTANCE_RADA_SENSOR 0x0745
#define RD_HEADER_CONFIG_TIME_RSP_SENSOR 0x0845
#define RD_HEADER_STATUS_DOOR_SENSOR 0x0009
#define RD_HEADER_STATUS_HANGON_DOOR_SENSOR 0x0409
#define RD_HEADER_CONFIG_SET_SCENE_SCREEN_TOUCH 0x010A
#define RD_HEADER_CONFIG_DEL_SCENE_SCREEN_TOUCH 0x020A
#define RD_HEADER_CONFIG_SEND_WEATHER_INDOOR 0x030A
#define RD_HEADER_CONFIG_SEND_WEATHER_OUTDOOR 0x050A
#define RD_HEADER_CONFIG_EDIT_ICON_SCREEN_TOUCH 0x070A
#define RD_HEADER_CONFIG_SEND_DATE 0x080A
#define RD_HEADER_CONFIG_SEND_TIME 0x090A
#define RD_HEADER_CONFIG_DEL_ALL_SCENE 0x0A0A
#define RD_HEADER_CONFIG_SET_GROUP 0x0B0A
#define RD_HEADER_CONFIG_ADD_ROOM 0x0C0A
#define RD_HEADER_CONFIG_DEL_ROOM 0x0D0A

#define RD_HEADER_CONFIG_CONTROL_RELAY_SWITCH_1 0x000E
#define RD_HEADER_CONFIG_CONTROL_RELAY_SWITCH_2 0x000D
#define RD_HEADER_CONFIG_CONTROL_RELAY_SWITCH_3 0x000C
#define RD_HEADER_CONFIG_CONTROL_RELAY_SWITCH_4 0x000B
#define RD_HEADER_CONFIG_STATUS_STARTUP_SWITCH 0x100B
#define RD_HEADER_CONFIG_STATUS_ALL_RELAY_SWITCH 0x110B
#define RD_HEADER_CONFIG_MODE_INPUT_SWITCHONOFF 0x0012

#define RD_HEADER_CONFIG_CONTROL_RGB_SWITCH 0x050B
#define RD_HEADER_CONFIG_SET_ID_COMBINE 0x060B
#define RD_HEADER_CONFIG_SET_TIMER 0x070B
#define RD_HEADER_REQUEST_STATUS_SWITCH_1 0x030e
#define RD_HEADER_REQUEST_STATUS_SWITCH_2 0x030d
#define RD_HEADER_REQUEST_STATUS_SWITCH_3 0x030c
#define RD_HEADER_REQUEST_STATUS_SWITCH_4 0x030b
#define RD_HEADER_REQUEST_STATUS_SWITCH 0x090B
#define RD_HEADER_CONTROL_OPEN_CLOSE_PAUSE 0x0011
#define RD_HEADER_RSP_CONTROL_OPEN_CLOSE_PAUSE_OPENED 0x0311
#define RD_HEADER_PRESS_BUTTON_CURTAN_DOOR_ROOLING 0x0611
#define RD_HEADER_CALIBAUTO 0x0711
#define RD_HEADER_LOCK 0x0811
#define RD_HEADER_MODE_WIFI 0x0911
#define RD_HEADER_CONFIG_MOTOR 0x0511
#define RD_HEADER_CALIB 0x0411
#define RD_HEADER_REQUEST_STATUS_CURTAIN 0x0311

#define RD_HEADER_SCREEN_TOUCH_PRESS 0x000A
#define RD_HEADER_SCREEN_TOUCH_REQUEST_TIME 0xF00A
#define RD_HEADER_SCREEN_TOUCH_REQUEST_TEMP 0xF10A

#define RD_HEADER_SEFTPOWER_REMOTE_SCAN 0x0a0b
#define RD_HEADER_SEFTPOWER_REMOTE_SAVE 0x0d0b
#define RD_HEADER_SEFTPOWER_REMOTE_RESET 0x0e0b
#define RD_HEADER_SEFTPOWER_REMOTE_PRESS 0x0b0b
#define RD_HEADER_SEFTPOWER_REMOTE_SET_SCENE 0x0c0b
#define RD_HEADER_SEFTPOWER_REMOTE_DEL_SCENE 0x0f0b

#define RD_HEADER_TEMP_HUM_AIR_STATUS_1 0x0006
#define RD_HEADER_TEMP_HUM_AIR_STATUS_2 0x0106
#define RD_HEADER_TEMP_SOIL_STATUS 0x1606
#define RD_HEADER_PH_SOIL_STATUS 0x1601
#define RD_HEADER_EC_SOIL_STATUS 0x1602
#define RD_HEADER_TEMP_WATER_STATUS 0x1706
#define RD_HEADER_EC_WATER_STATUS 0x1702
#define RD_HEADER_PH_WATER_STATUS 0x1701
#define RD_HEADER_OXY_WATER_STATUS 0x1703
#define RD_HEADER_EC_SALI_TDS_WATER 0x1704

#define RD_HEADER_STATUS_TEMP_HUM_OF_PM 0x0107
#define RD_HEADER_STATUS_PM 0x0207
#define RD_HEADER_STATUS_SMOKE 0x0108

#define RD_HEADER_STATUS_IN_MODULE_INOUT 0x0115
#define RD_HEADER_STATUS_ADC_MODULE_INOUT 0x0215
#define RD_HEADER_CONFIG_MODE_INPUT_MODULE_INOUT 0x0315
#define RD_HEADER_CONFIG_COMBINE_MODULE_INOUT 0x0415
#define RD_HEADER_SETSCENE_MODULE_INOUT 0x0515
#define RD_HEADER_CONFIG_DELTA_ADC 0x0715
#define RD_HEADER_CONFIG_STATUS_STARTUP_RELAY 0x0815

#define TRANSITION_DEFAULT 5

#define CONNECT_DEVICE_TIMEOUT 40 // seconds
#define BLE_MAX_ELEMENT 4

// OLD
#define PROV_OWN_ADDR 0x0001

#define MSG_SEND_TTL 3
#define MSG_SEND_REL false
#define MSG_TIMEOUT 0
#define MSG_ROLE ROLE_PROVISIONER

#define COMP_DATA_PAGE_0 0x00

#define APP_KEY_IDX 0x0000
#define APP_KEY_OCTET 0x12

#define COMP_DATA_1_OCTET(msg, offset) (msg[offset])
#define COMP_DATA_2_OCTET(msg, offset) (msg[offset + 1] << 8 | msg[offset])

#define ESP_BLE_MESH_VND_MODEL_ID_CLIENT 0x0000
#define ESP_BLE_MESH_VND_MODEL_ID_SERVER 0x0001

// #define ESP_BLE_MESH_VND_MODEL_OP_SEND ESP_BLE_MESH_MODEL_OP_3(0x00, RD_VENDOR_ID)
// #define ESP_BLE_MESH_VND_MODEL_OP_STATUS ESP_BLE_MESH_MODEL_OP_3(0x01, RD_VENDOR_ID)

#define ESP_BLE_MESH_MODEL_OP_4(b0, cid) ((((b0) << 16) | 0xE20000) | (cid))            ///< Get opcode of Vendor Model
#define ESP_BLE_MESH_VND_MODEL_OP_SEND_E2 ESP_BLE_MESH_MODEL_OP_4(0x00, RD_VENDOR_ID)   ///< SEND Opcode of Vendor Model
#define ESP_BLE_MESH_VND_MODEL_OP_STATUS_E2 ESP_BLE_MESH_MODEL_OP_4(0x01, RD_VENDOR_ID) ///< STATUS Opcode Send of Vendor Model
#define ESP_BLE_MESH_MODEL_OP_5(b0, cid) ((((b0) << 16) | 0xE00000) | (cid))            ///< Get Opcode of Vendor Model
#define ESP_BLE_MESH_VND_MODEL_OP_SEND_E0 ESP_BLE_MESH_MODEL_OP_5(0x00, RD_VENDOR_ID)   ///< SEND Opcode of Vendor Model
#define ESP_BLE_MESH_VND_MODEL_OP_STATUS_E0 ESP_BLE_MESH_MODEL_OP_5(0x01, RD_VENDOR_ID) ///< STATUS Opcode Send of Vendor Model